Generate Codable extensions adhering to `ExistentialAny`
SwiftyLab/MetaCodable pull request #29
Opened 2023-10-12 21:01 UTC by tomasharkema

Swift 5.9 added `ExistentialAny`, which can be enabled by the swift setting: `.enableUpcomingFeature("ExistentialAny")`. The source that will be generated is backwards compatible.

I also took te liberty to run `swiftformat`, I hope it doesn't make the PR too cluttered. 🙈

2023-10-12 21:05 UTC, tomasharkema commented on Sources/CodableMacroPlugin/Registration/Registrar.swift
> +            type: IdentifierTypeSyntax(name: "any Decoder")
Here is any added to the type

2023-10-12 21:05 UTC, tomasharkema commented on Sources/CodableMacroPlugin/Registration/Registrar.swift
> +            type: IdentifierTypeSyntax(name: "any Encoder")
idem

2023-10-12 21:07 UTC, tomasharkema commented on Package.swift
> +                .enableUpcomingFeature("ExistentialAny"),
This change will be optional, if you don't want to enable this in the codebase, this can be removed.

2023-10-13 08:08 UTC, soumyamahunt commented on Sources/CodableMacroPlugin/Registration/Registrar.swift
> +            type: IdentifierTypeSyntax(name: "any Encoder")
I don't think `any Encoder` is type of `IdentifierTypeSyntax` in swift-syntax, please check [here](https://swift-ast-explorer.com/) the actual type. You can try `"any Encoder" as TypeSyntax` as well.

2023-10-13 08:08 UTC, soumyamahunt commented on Sources/CodableMacroPlugin/Registration/Registrar.swift
> +            type: IdentifierTypeSyntax(name: "any Decoder")
Please check [this](https://github.com/SwiftyLab/MetaCodable/pull/29#discussion_r1357915308).

2023-10-13 08:11 UTC, soumyamahunt commented on Package.swift
> +                .enableUpcomingFeature("ExistentialAny"),
As far as I know, this feature will only be applied to specific module not entire app, if that's the case then I am fine with it.

2023-10-13 08:24 UTC, soumyamahunt requested changes

2023-10-13 08:24 UTC, soumyamahunt commented on .swift-version
> +5.9
Is this needed with Swift packages, anyway `swift-tools-version` is mentioned in package manifest.

2023-10-13 08:28 UTC, soumyamahunt commented
> I also took te liberty to run `swiftformat`, I hope it doesn't make the PR too cluttered. 🙈

What command did you use to run swift-format? I don't see these changes when running swift-format.

The recommended way for running swift-format for this library would be to run:
```sh
npm run format
```

which runs:

```sh
swift run swift-format --in-place --ignore-unparsable-files --recursive Sources Tests
```

2023-11-03 15:09 UTC, soumyamahunt commented
@tomasharkema I am planning to release all the pending fixes next week, let me know if you can resolve the comments and rebase by then.

2023-11-06 11:00 UTC, soumyamahunt commented
superseded by #34.

2023-11-06 11:00 UTC, closed without merging