feat: support implicitly unwrapped optional type
SwiftyLab/MetaCodable pull request #87
Opened 2024-05-30 12:23 UTC by hstdt

Fix this situation:

```
@Codable
    struct SomeCodable {
        let value: String!
}
```
![CleanShot 2024-05-30 at 20 22 52](https://github.com/SwiftyLab/MetaCodable/assets/10215098/44f3c970-b450-419e-98d6-5640df84813c)

2024-05-31 04:14 UTC, hstdt commented
commit above fixed error with`@Default` macro

<img width="2134" alt="image" src="https://github.com/SwiftyLab/MetaCodable/assets/10215098/adcc259f-d4ea-4492-a14f-774232dc718f">

2024-05-31 06:55 UTC, hstdt commented
@soumyamahunt tests added.

if the last commit of tests is not necessary, i'll revert it.

2024-05-31 07:00 UTC, hstdt commented
PS: 
The expanded code of `testWithNestedPathOnMixedTypes()` and `testClassWithNestedPathOnMixedTypes()` in `CodedInDefaultTests` is not compilable(not related to this pull request): "Return from initializer without initializing all stored properties"

2024-06-06 04:31 UTC, soumyamahunt commented
> PS: The expanded code of `testWithNestedPathOnMixedTypes()` and `testClassWithNestedPathOnMixedTypes()` in `CodedInDefaultTests` is not compilable(not related to this pull request): "Return from initializer without initializing all stored properties"

Thanks for reporting this, this has been fixed. Please rebase your branch and update test cases if needed.

2024-06-06 20:02 UTC, soumyamahunt requested changes

2024-06-06 20:02 UTC, soumyamahunt commented on Sources/PluginCore/Variables/Property/BasicPropertyVariable.swift
> +            let type: TypeSyntax = type.is(ImplicitlyUnwrappedOptionalTypeSyntax.self) ? TypeSyntax(OptionalTypeSyntax(wrappedType: type.as(ImplicitlyUnwrappedOptionalTypeSyntax.self)!.wrappedType))
This can be written in a more readable way with if-let expression

2024-06-07 02:59 UTC, hstdt commented
@soumyamahunt updated

2024-06-07 05:26 UTC, soumyamahunt approved these changes
@hstdt changes LGTM, anything else you would like to add or should I merge this?

2024-06-07 05:50 UTC, hstdt commented
@soumyamahunt Nothing else to add. Please merge it.

2024-06-07 05:52 UTC, merged